### ISSUE TITLE
Automagically prepend -Wl, to linker flags as needed

### ISSUE THREAD

**Issue by Ipsum** [jimporter/bfg9000#114]
It would be really nice if BFG could figure out when to prepend `-Wl,` to my linker flags. For example, we are using `--gc-sections` in `global_link_options()` and you are both compiling and linking with gcc you need to prepend the linker flags with `-Wl,`. However, if you simply create .o's and link with ld, you do not need the `-Wl,`.

**Comment by jimporter** [comment]
I don't think it's actually possible to use `ld` directly in bfg (it makes a lot of simple tasks more complex to manage); on `master`, even setting the `LD` enviroment variable really just tells bfg to use `gcc -fuse-ld=<whatever>`, rather than using `ld` "raw".

Maybe it'd be nice to have some sort of semantic option that says "these values should be forwarded directly to the linker", but I'm not sure it'd be any easier to read:

```python
['-Wl,--push-state,--as-needed', ...]
# versus
[opts.ld('--push-state', '--as-needed'), ...]
```

It's not really feasible to do it 100% automatically, since that means keeping track of every possible option for GCC to know when to avoid adding `-Wl,`. There are even some conflicting option names, like `-S`, which tells GCC to stop after generating assembly files (possibly useful during debugging), but tells LD to strip debugger symbols from the output. I think `-lobjc` is also something that gets handled specially by GCC.

**Comment by Ipsum** [comment]
I think I was mostly just surprised that the specific function `global_link_options` did not do this. You do make a good point though because I guess there are linker flags that do not necessarily need -Wl

**Comment by jimporter** [comment]
It's probably worth adding some documentation here, since anyone used to using `ld` raw would be surprised that `link_options` passes through GCC first.
