### ISSUE TITLE
build_step: buldstep.output not always consumed by tools: how to create explicitly the dependency

### ISSUE THREAD

**Issue by zokrezyl** [jimporter/bfg9000#134]
Some tools like protoc do not consume as argument output filenames but an output directory. I failed to write a custom step that would link as dependency the output of protoc with another build step for this reason.

I think there should be another parameter of the build_step that would make someway the output of such a custom step explicitly dependency of another step. In the example https://github.com/jimporter/bfg9000/tree/master/examples/09_custom_steps it seems that the key to "link" the dependency with the dependant is the usage of build_step.output, however in the real case scenario with protoc this is not possible, unless I write a wrapper around protoc that will ignore that argument.

**Comment by jimporter** [comment]
It's generally pretty risky to use a build step whose output is a directory due to how the modification times on directories work on most platforms. They only count as "modified" is the list of files within the directory changes, which is a problem since you might update an input file in a way that doesn't change the list of output files, resulting in your input always having a later mtime than your output directory. It's possible `protoc` handles this, but probably not. If it did, then the solution would be something like:

```python
incdir = build_step('outdir', cmd=[
    'protoc', '--cpp-out', build_step.output, build_step.input
], files=['input.txt'], type=header_directory)
# same as...
proto = generic_file('input.txt')
incdir = build_step('outdir', cmd=['protoc', '--cpp-out', build_step.output, proto],
               type=header_directory)

executable(..., includes=[incdir])
```

Since `protoc` probably doesn't handle this, the most-reliable way to manage the dependencies would be to specify the output as the "primary" header file that you'd use when building your program, and then just specify the outdir as a string:

```python
hdr = build_step('outdir/header.hpp', cmd=[
    'protoc', '--cpp-out=outdir', build_step.input
], files=['input.txt'])
executable(..., includes=[hdr])
```

Since commands are executed from the builddir, the shell will interpret the string `outdir` as relative to the root of the builddir. This should work if your source contains `#include "header.hpp"`. If your source contained `#include "outdir/header.hpp"`, this is a little more complex. You'd need to replace the last line with:

```python
incdir= hdr.path.parent().parent()  # get the path
executable(..., includes=[incdir], extra_compile_deps=[hdr])
```

If you wanted to be extra-explicit with creating a path pointing to the builddir (or the srcdir), you could explicitly create a [`Path`](https://jimporter.github.io/bfg9000/latest/user/reference/#Path) object: `Path('outdir')`. That's not really necessary here though.

**Comment by zokrezyl** [comment]
Thanks for the verbose explanation. However I think one has to make a difference between the correctness of the tool used in a build step and the times used to trigger the build step. protoc does not need to accept the output filenames as pramater in order to write correct rules that would create those files. What I mean is I can describe in a Makefile like syntax

```
out1 out2: in1
        ./tool in1
```
where tool is
```
#!/usr/bin/env bash
touch out1 out2
```

if I change in1, out1 and out2 will be correctly rebuilt.

Did not check this with Ninja, but it should be the same.

Therefore what would expect from bfg9000 is to create an implicit dependency and just do not try to use the output filenams in production rules.

**Comment by jimporter** [comment]
That also works in bfg9000:

```python
out1, out2 = build_step(
    ['out1', 'out2'],
    cmd=['tool', build_step.input],
    files=['in1']
)

# or...

in1 = generic_file('in1')
out1, out2 = build_step(
    ['out1', 'out2'],
    cmd=['tool', in1]
)
```

Both of those will produce exactly the same rule in the build backend. For example, the generated Makefile looks like this:

```make
out1 out2: out1.stamp

out1.stamp: $(srcdir)/in1
        tool '$(srcdir)/in1'
        @touch '$@'
```

This is a bit more complex than your example Make rule, since multiple outputs in a Make rule [don't work the way you might expect](https://www.gnu.org/software/automake/manual/html_node/Multiple-Outputs.html). If there were a single output, the generated Make rule would look like this:

```make
out: $(srcdir)/in1
        tool '$(srcdir)/in1'
```

**Comment by jimporter** [comment]
Closing this for now. If you're still having issues with this though, free free to comment here again and I'll try to answer any further questions or fix issues related to this.
