### ISSUE TITLE
Continuous Integration testing for Windows

### ISSUE THREAD

**Issue by nlhepler** [jimporter/bfg9000#40]
Evaluate using a continuous integration service:
- [CircleCI](https://circleci.com)
- [TravisCI](https://travis-ci.org)

**Comment by kirbyfan64** [comment]
+1 for Travis. I've used it several times, and it even supports also running tests under OSX.

**Comment by jimporter** [comment]
The important part of CI is really testing Windows. I (almost) always test on Linux before merging anything, and OS X is pretty close to Linux in most ways (except its linker is a little weird). Windows, on the other hand, has the MSBuild backend, its default compiler has a totally different interface, and necessitates a different file structure for installed binaries due to how its shared library loader works.

**Comment by kirbyfan64** [comment]
For Windows, you can use AppVeyor.

**Comment by jimporter** [comment]
@nlhepler I've added support for testing OS X on Travis now. It was a pain in the ass, since Travis doesn't let you test Python on OS X by default, but I managed to outsmart them. See https://github.com/travis-ci/travis-ci/issues/2312 for more details.

**Comment by jimporter** [comment]
Appveyor builds are go, and I fixed a few bugs that had accumulated since the last time I booted up my Windows VM. About the only thing I need to do before releasing 0.1 now is to write up some more docs.
