### ISSUE TITLE
macOS frameworks/platform specific code

### ISSUE THREAD

**Issue by block8437** [jimporter/bfg9000#77]
I was wondering if there was a way, and if not if there could be, to have platform specific code. Linking OpenGL on macOS is done via `-framework OpenGL` (which is different than how it is linked in Windows/Linux). How could/should this be done in bfg9000?

**Comment by jimporter** [comment]
The easiest way would be if you have pkg-config on all your platforms; then you can just say

```python
ogl = pkgconfig_package('opengl')
executable('my_program', files=['main.cpp'], packages=[ogl])
```

Otherwise, you can check [`env.platform.name`](https://jimporter.github.io/bfg9000/user/reference/#platform-name):

```python
if env.platform.name == 'darwin':
    ldflags = ['-framework', 'OpenGL']
else:
    ldflags = ['-lGL']
executable('my_program', files=['main.cpp'], link_options=ldflags)
```

Incidentally, if you think I should change macOS's platform name away from `'darwin'`, now's the time to suggest it since bfg is still in early development and doesn't need to worry too much about backward compatibility. :)

**Comment by jimporter** [comment]
Reading about this more, it seems like something that's pretty annoying for users to get right, so I'm going to try to come up with a way for this to Just Work. Maybe something like:

```python
ogl = package('opengl')
```

And then I could just special-case "opengl" to find libraries as appropriate.

**Comment by jimporter** [comment]
@block8437 If you're feeling adventurous, the latest master revision now supports this easily. Just use the following and you should get OpenGL on every platform (well, Windows, Mac, and Linux at least):

```python
gl = package('gl')
executable('program', files=['main.cpp'], packages=[gl])
```
